# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vdpOAXhE7EEOqZaH9LLJ_iddlCFL3CH3
"""

# Установка и импорты

!pip install catboost lightgbm -q

import re
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.sparse import hstack, csr_matrix
from scipy.stats import rankdata

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import average_precision_score, roc_auc_score, precision_recall_curve

from catboost import CatBoostClassifier, Pool
from lightgbm import LGBMClassifier

# Загрузка данных


df = pd.read_csv("/content/public_dataset.csv")

print("Shape:", df.shape)
print("\nРаспределение таргета:")
print(df["target"].value_counts())
print(f"Доля label=1: {df['target'].mean():.3f}")
print("\nПропуски:")
print(df.isnull().sum())

# Первичный анализ длины текста
# Короткие названия хуже поддаются матчингу — проверяем гипотезу

df["text_length"] = df["supplier_room_name"].fillna("").apply(len)
df["word_count"]  = df["supplier_room_name"].fillna("").apply(lambda x: len(x.split()))

print("\nСредняя длина текста по классам:")
print(df.groupby("target")[["text_length", "word_count"]].mean().round(2))

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
df[df["target"]==0]["text_length"].hist(bins=50, alpha=0.7, color="steelblue", label="label=0")
df[df["target"]==1]["text_length"].hist(bins=50, alpha=0.7, color="orange",    label="label=1")
plt.title("Длина текста по классам")
plt.legend()
plt.subplot(1, 2, 2)
df["word_count"].hist(bins=50, color="steelblue")
plt.title("Количество слов в названии")
plt.tight_layout()
plt.show()

# Разбивка на train / val / test
# Используем random split: отели пересекаются между выборками,
# поэтому hotel-статистики считаем только на трейне и переносим на val/test

df_train_val, df_test = train_test_split(
    df, test_size=0.20, random_state=42, stratify=df["target"]
)
df_train, df_val = train_test_split(
    df_train_val, test_size=0.15, random_state=42, stratify=df_train_val["target"]
)

print(f"Train: {len(df_train)} строк")
print(f"Val:   {len(df_val)} строк")
print(f"Test:  {len(df_test)} строк  ← 20% холдаут для финальной оценки")
print(f"\nДоля label=1  train: {df_train['target'].mean():.3f}")
print(f"Доля label=1  val:   {df_val['target'].mean():.3f}")
print(f"Доля label=1  test:  {df_test['target'].mean():.3f}")

# Предобработка текста
# Приводим к нижнему регистру, оставляем только буквы и цифры обоих языков
# Строки из одного слова или чисел удаляем — они неинформативны

def preprocess_text(text):
    if not isinstance(text, str) or text.strip() == "":
        return None
    original = text.strip()
    if re.fullmatch(r'[\d\s\W]+', original):
        return None
    text = original.lower()
    text = re.sub(r'[^a-zа-яё0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    if len(text.split()) < 2:
        return None
    return text

df_train["text_clean"] = df_train["supplier_room_name"].apply(preprocess_text)
df_val["text_clean"]   = df_val["supplier_room_name"].apply(preprocess_text)
df_test["text_clean"]  = df_test["supplier_room_name"].apply(preprocess_text)

before_train = len(df_train)
before_val   = len(df_val)
df_train = df_train.dropna(subset=["text_clean"]).copy()
df_val   = df_val.dropna(subset=["text_clean"]).copy()
df_test["text_clean"] = df_test["text_clean"].fillna("")

print(f"Train: {before_train} → {len(df_train)} (удалено {before_train - len(df_train)} пустых)")
print(f"Val:   {before_val} → {len(df_val)}")

# удаляем полные дубликаты из трейна
before = len(df_train)
df_train = df_train.drop_duplicates(
    subset=["hotel_id", "supplier_room_name", "target"]
).copy()
print(f"Дубликаты удалены: {before} → {len(df_train)}")

# Hotel-статистики
# Считаем только на трейне, чтобы не было утечки данных
# hotel_positive_rate — доля несматченных номеров по отелю

hotel_stats = df_train.groupby("hotel_id")["target"].agg(
    hotel_positive_rate="mean",
    hotel_room_count="count",
    hotel_target_std="std"
).reset_index()
hotel_stats["hotel_target_std"] = hotel_stats["hotel_target_std"].fillna(0)

df_train = df_train.merge(hotel_stats, on="hotel_id", how="left")
df_val   = df_val.merge(hotel_stats,   on="hotel_id", how="left")
df_test  = df_test.merge(hotel_stats,  on="hotel_id", how="left")

global_mean = df_train["target"].mean()
for df_ in [df_val, df_test]:
    df_["hotel_positive_rate"] = df_["hotel_positive_rate"].fillna(global_mean)
    df_["hotel_room_count"]    = df_["hotel_room_count"].fillna(0)
    df_["hotel_target_std"]    = df_["hotel_target_std"].fillna(0)

print("Hotel-статистики добавлены")

# Ручные признаки
# Основаны на бизнес-атрибутах из постановки задачи
# тип кровати, уровень номера, вид, балкон, семейный номер

def add_features(df_):
    df_  = df_.copy()
    text = df_["text_clean"].fillna("")
    orig = df_["supplier_room_name"].fillna("")

    df_["text_length"]     = orig.apply(len)
    df_["word_count"]      = text.apply(lambda x: len(x.split()))
    df_["unique_ratio"]    = text.apply(
        lambda x: len(set(x.split())) / max(len(x.split()), 1)
    )
    df_["upper_ratio"]     = orig.apply(
        lambda x: sum(1 for c in x if c.isupper()) / max(len(x), 1)
    )
    df_["has_parentheses"] = orig.apply(lambda x: int("(" in x))
    df_["digit_count"]     = orig.apply(
        lambda x: sum(1 for c in x if c.isdigit())
    )
    df_["ru_ratio"] = text.apply(
        lambda x: sum(1 for c in x if 'а' <= c <= 'я' or c == 'ё') / max(len(x), 1)
    )
    df_["en_ratio"] = text.apply(
        lambda x: sum(1 for c in x if 'a' <= c <= 'z') / max(len(x), 1)
    )

    bed_configs = [
        "king", "queen", "twin", "double", "single", "bunk",
        "двуспальн", "односпальн", "1 bed", "2 bed",
        "1 кровать", "2 кровати", "2 отдельные"
    ]
    df_["has_bed_config"] = text.apply(
        lambda x: int(any(b in x for b in bed_configs))
    )

    room_levels = [
        "standard", "стандарт", "deluxe", "делюкс",
        "superior", "executive", "premium", "премиум",
        "classic", "comfort", "комфорт", "люкс", "economy"
    ]
    df_["has_room_level"] = text.apply(
        lambda x: int(any(r in x for r in room_levels))
    )

    view_words = [
        "sea view", "ocean view", "вид на море",
        "city view", "вид на город", "garden view",
        "pool view", "mountain view", " view", " вид"
    ]
    df_["has_view"] = text.apply(
        lambda x: int(any(v in x for v in view_words))
    )

    balcony_words = ["balcon", "terrace", "террас", "балкон", "лоджия"]
    df_["has_balcony"] = text.apply(
        lambda x: int(any(b in x for b in balcony_words))
    )

    family_words = ["family", "семейн", "child", "детск", "kids"]
    df_["is_family"] = text.apply(
        lambda x: int(any(f in x for f in family_words))
    )

    biz = ["has_bed_config", "has_room_level", "has_view", "has_balcony", "is_family"]
    df_["business_completeness"] = df_[biz].sum(axis=1) / len(biz)

    return df_

df_train = add_features(df_train)
df_val   = add_features(df_val)
df_test  = add_features(df_test)

feature_cols = [
    "text_length", "word_count", "unique_ratio", "upper_ratio",
    "has_parentheses", "digit_count", "ru_ratio", "en_ratio",
    "has_bed_config", "has_room_level", "has_view",
    "has_balcony", "is_family", "business_completeness",
    "hotel_positive_rate", "hotel_room_count", "hotel_target_std"
]

print("Признаки добавлены")
print(f"\nСреднее значение признаков по классам:")
print(df_train.groupby("target")[feature_cols].mean().round(3).T)

# CatBoost
# Используем ручные признаки + сырой текст одновременно

X_train_cb = df_train[feature_cols + ["text_clean"]].fillna("")
X_val_cb   = df_val[feature_cols   + ["text_clean"]].fillna("")

train_pool = Pool(data=X_train_cb, label=df_train["target"], text_features=["text_clean"])
val_pool   = Pool(data=X_val_cb,   label=df_val["target"],   text_features=["text_clean"])

print("Обучаем CatBoost...")
model_cb = CatBoostClassifier(
    iterations=3000,
    learning_rate=0.03,
    depth=6,
    eval_metric="AUC",
    random_seed=42,
    verbose=200,
    l2_leaf_reg=5,
    min_data_in_leaf=20,
)
model_cb.fit(train_pool, eval_set=val_pool, early_stopping_rounds=150)

y_val_proba_cb = model_cb.predict_proba(val_pool)[:, 1]
pr_auc_cb  = average_precision_score(df_val["target"], y_val_proba_cb)
roc_auc_cb = roc_auc_score(df_val["target"], y_val_proba_cb)

print(f"\nCatBoost  PR-AUC:  {pr_auc_cb:.4f}")
print(f"CatBoost  ROC-AUC: {roc_auc_cb:.4f}")

# важность признаков
imp_df = pd.DataFrame({
    "feature":    feature_cols + ["text_clean"],
    "importance": model_cb.get_feature_importance()
}).sort_values("importance", ascending=False)
print("\nТоп-10 важных признаков:")
print(imp_df.head(10).to_string(index=False))

#LightGBM v1
# Объединяем TF-IDF матрицу с ручными признаками через sparse hstack

tfidf = TfidfVectorizer(max_features=1000, ngram_range=(1, 2))
X_tfidf_train = tfidf.fit_transform(df_train["text_clean"].fillna(""))
X_tfidf_val   = tfidf.transform(df_val["text_clean"].fillna(""))

X_manual_train = df_train[feature_cols].fillna(0).values
X_manual_val   = df_val[feature_cols].fillna(0).values

X_train_lgbm = hstack([X_tfidf_train, csr_matrix(X_manual_train)])
X_val_lgbm   = hstack([X_tfidf_val,   csr_matrix(X_manual_val)])

print("Обучаем LightGBM v1 (TF-IDF 1000 фич, биграммы)...")
lgbm = LGBMClassifier(
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=63,
    random_state=42,
    n_jobs=-1,
    verbose=-1
)
lgbm.fit(
    X_train_lgbm, df_train["target"],
    eval_set=[(X_val_lgbm, df_val["target"])],
    callbacks=[
        LGBMClassifier.__module__ and __import__('lightgbm').early_stopping(150, verbose=True),
        __import__('lightgbm').log_evaluation(500)
    ]
)

y_val_proba_lgbm = lgbm.predict_proba(X_val_lgbm)[:, 1]
pr_auc_lgbm  = average_precision_score(df_val["target"], y_val_proba_lgbm)
roc_auc_lgbm = roc_auc_score(df_val["target"], y_val_proba_lgbm)

print(f"\nLightGBM v1  PR-AUC:  {pr_auc_lgbm:.4f}")
print(f"LightGBM v1  ROC-AUC: {roc_auc_lgbm:.4f}")

#LightGBM v2
# Расширяем словарь до 5000 фич и добавляем триграммы
# Увеличиваем num_leaves до 127
# Early stopping срабатывает раньше чем у v1

tfidf2 = TfidfVectorizer(max_features=5000, ngram_range=(1, 3))
X_tfidf_train2 = tfidf2.fit_transform(df_train["text_clean"].fillna(""))
X_tfidf_val2   = tfidf2.transform(df_val["text_clean"].fillna(""))

X_train_lgbm2 = hstack([X_tfidf_train2, csr_matrix(X_manual_train)])
X_val_lgbm2   = hstack([X_tfidf_val2,   csr_matrix(X_manual_val)])

print("Обучаем LightGBM v2 (TF-IDF 5000 фич, триграммы)...")
lgbm2 = LGBMClassifier(
    n_estimators=3000,
    learning_rate=0.03,
    num_leaves=127,
    random_state=42,
    n_jobs=-1,
    verbose=-1
)
lgbm2.fit(
    X_train_lgbm2, df_train["target"],
    eval_set=[(X_val_lgbm2, df_val["target"])],
    callbacks=[
        __import__('lightgbm').early_stopping(150, verbose=True),
        __import__('lightgbm').log_evaluation(500)
    ]
)

y_val_proba_lgbm2 = lgbm2.predict_proba(X_val_lgbm2)[:, 1]
pr_auc_lgbm2  = average_precision_score(df_val["target"], y_val_proba_lgbm2)
roc_auc_lgbm2 = roc_auc_score(df_val["target"], y_val_proba_lgbm2)

print(f"\nLightGBM v2  PR-AUC:  {pr_auc_lgbm2:.4f}")
print(f"LightGBM v2  ROC-AUC: {roc_auc_lgbm2:.4f}")

#Ensemble
# Ансамблируем три модели
# Перебираем веса сеткой и выбираем лучшую комбинацию по PR-AUC
# Дополнительно проверяем ранговое усреднение (rank averaging)

rank_lgbm  = rankdata(y_val_proba_lgbm)  / len(y_val_proba_lgbm)
rank_lgbm2 = rankdata(y_val_proba_lgbm2) / len(y_val_proba_lgbm2)
rank_cb    = rankdata(y_val_proba_cb)    / len(y_val_proba_cb)

best_score  = 0.0
best_blend  = None
best_params = None

for w1 in np.arange(0.1, 0.9, 0.05):
    for w2 in np.arange(0.1, 0.9 - w1, 0.05):
        w3 = round(1 - w1 - w2, 4)
        prob_blend = w1*y_val_proba_lgbm + w2*y_val_proba_lgbm2 + w3*y_val_proba_cb
        rank_blend = w1*rank_lgbm        + w2*rank_lgbm2        + w3*rank_cb
        for blend in [prob_blend, rank_blend]:
            s = average_precision_score(df_val["target"], blend)
            if s > best_score:
                best_score  = s
                best_blend  = blend
                best_params = (w1, w2, w3)

print(f"\n{'='*45}")
print(f"CatBoost:       PR-AUC = {pr_auc_cb:.4f}")
print(f"LightGBM v1:    PR-AUC = {pr_auc_lgbm:.4f}")
print(f"LightGBM v2:    PR-AUC = {pr_auc_lgbm2:.4f}")
print(f"Ensemble:       PR-AUC = {best_score:.4f}  ← лучший результат")
print(f"Веса (lgb1/lgb2/cb): {best_params}")
print(f"{'='*45}")

# Оценка на тестовом холдауте
# Применяем финальный ансамбль к тестовой выборке,
# которая не участвовала ни в обучении, ни в подборе весов

X_test_cb = df_test[feature_cols + ["text_clean"]].fillna("")
test_pool  = Pool(data=X_test_cb, label=df_test["target"], text_features=["text_clean"])
test_proba_cb = model_cb.predict_proba(test_pool)[:, 1]

X_tfidf_test  = tfidf.transform(df_test["text_clean"].fillna(""))
X_tfidf_test2 = tfidf2.transform(df_test["text_clean"].fillna(""))
X_manual_test = df_test[feature_cols].fillna(0).values
X_test_lgbm   = hstack([X_tfidf_test,  csr_matrix(X_manual_test)])
X_test_lgbm2  = hstack([X_tfidf_test2, csr_matrix(X_manual_test)])

test_proba_lgbm  = lgbm.predict_proba(X_test_lgbm)[:, 1]
test_proba_lgbm2 = lgbm2.predict_proba(X_test_lgbm2)[:, 1]

w1, w2, w3 = best_params
test_ensemble = w1*test_proba_lgbm + w2*test_proba_lgbm2 + w3*test_proba_cb

pr_auc_test = average_precision_score(df_test["target"], test_ensemble)
print(f"\nФинальный PR-AUC на тестовом холдауте (20%): {pr_auc_test:.4f}")

#PR-кривая

prec_cb,   rec_cb,   _ = precision_recall_curve(df_test["target"], test_proba_cb)
prec_lgb,  rec_lgb,  _ = precision_recall_curve(df_test["target"], test_proba_lgbm)
prec_lgb2, rec_lgb2, _ = precision_recall_curve(df_test["target"], test_proba_lgbm2)
prec_ens,  rec_ens,  _ = precision_recall_curve(df_test["target"], test_ensemble)

plt.figure(figsize=(9, 6))
plt.plot(rec_cb,   prec_cb,   lw=1.5, alpha=0.6, color='#4C9BE8',
         label=f'CatBoost      PR-AUC={average_precision_score(df_test["target"], test_proba_cb):.4f}')
plt.plot(rec_lgb,  prec_lgb,  lw=1.5, alpha=0.6, color='#E8734C',
         label=f'LightGBM v1   PR-AUC={average_precision_score(df_test["target"], test_proba_lgbm):.4f}')
plt.plot(rec_lgb2, prec_lgb2, lw=1.5, alpha=0.6, color='#9B59B6',
         label=f'LightGBM v2   PR-AUC={average_precision_score(df_test["target"], test_proba_lgbm2):.4f}')
plt.plot(rec_ens,  prec_ens,  lw=2.5, color='#2ECC71',
         label=f'Ensemble       PR-AUC={pr_auc_test:.4f}')
plt.axhline(df_test["target"].mean(), color='gray', linestyle='--',
            label=f'Baseline = {df_test["target"].mean():.3f}')
plt.xlabel('Recall', fontsize=12)
plt.ylabel('Precision', fontsize=12)
plt.title('Precision-Recall Curve — тестовый холдаут 20%', fontsize=13)
plt.legend(fontsize=10)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('pr_curve_final.png', dpi=150)
plt.show()
print('PR-кривая сохранена в pr_curve_final.png')

# Сохранение моделей

with open('model_cb.pkl',   'wb') as f: pickle.dump(model_cb,  f)
with open('model_lgbm.pkl', 'wb') as f: pickle.dump(lgbm,      f)
with open('model_lgbm2.pkl','wb') as f: pickle.dump(lgbm2,     f)
with open('tfidf.pkl',      'wb') as f: pickle.dump(tfidf,     f)
with open('tfidf2.pkl',     'wb') as f: pickle.dump(tfidf2,    f)

np.save('best_params.npy', np.array(best_params))
print('Все модели сохранены')